language: go

matrix:
  fast_finish: true
  include:
    - os: linux
      env: DISTRODETECT="Linux (Debian Stretch 9)"
      script: tests/debian/run.sh
    - os: linux
      dist: trusty
      env: DISTRODETECT="Linux (Ubuntu Trusty 14.04)"
    - os: linux
      dist: precise
      env: DISTRODETECT="Linux (Ubuntu Precise 12.04)"
    - os: osx
      before_install: sw_vers
      osx_image: xcode7.2
      env: DISTRODETECT="OS X (High Sierra 10.13.3)"
    - os: linux
      env: DISTRODETECT="Linux (Void Linux)"
      script: tests/void/run.sh
    - os: linux
      env: DISTRODETECT="Linux (Arch Linux)"
      script: tests/arch/run.sh
