language: go

services:
  -docker

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env:
        - DISTRODETECT="Linux (Ubuntu Trusty 14.04)"
    - os: linux
      dist: precise
      sudo: false
      env:
        - DISTRODETECT="Linux (Ubuntu Precise 12.04)"
    - os: osx
      before_install: sw_vers
      osx_image: xcode7.2
      env:
        - DISTRODETECT="OS X (10.13.3)"

script:
  - tests/void/run.sh
